# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "catppuccin_latte", "catppuccin_mocha"

# Site Settings
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "Stanley Lageweg"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Stanley Lageweg"
description              : "Senior Game Programmer"
url                      : "https://stanleylageweg.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "StanleyLageweg/StanleyLageweg.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
words_per_minute         : 200
enable_copy_code_button  : # true, false (default)
copyright                : "Stanley Lageweg" # "copyright" name, defaults to site.title
copyright_url            : "https://github.com/StanleyLageweg/stanleylageweg.github.io/blob/master/LICENSE" # "copyright" URL, defaults to site.url
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
og_image_alt             : # Alt text for Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : "Stanley Lageweg" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Stanley Lageweg"
  avatar           : "/assets/images/stanley.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I'm a senior programmer with 6 years of experience in game development, specializing in user-facing interactive systems. I love collaborating in varied teams, to create something greater than the sum of its parts. Challenging work is what keeps me motivated, whether it's creating clean code architectures, solving complex 3D math problems or tweaking a feature to get the feel just right."
  location         : "Alphen aan den Rijn, Netherlands"
  # fediverse      : "@you@instance.social"  # used for fediverse:creator meta tag
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stanley-lageweg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/StanleyLageweg"
    - label: "Resume"
      icon: "fa-regular fa-file"
      url: "/assets/files/resume.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-square-facebook"
      # url: "https://facebook.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url: "https://gitlab.com/"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      # url: "https://stackoverflow.com/"
    - label: "CodePen"
      icon: "fab fa-fw fa-codepen"
      # url: "https://codepen.io/"
    - label: "steam"
      icon: "fab fa-fw fa-steam"
      # url: "https://steamcommunity.com/"
    


# Reading Files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .bundle
  - .sass-cache
  - Gemfile
  - LICENSE
  - NOTICE.md
  - log
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  math_engine: katex
  math_engine_opts:
    output: mathml
    throw_on_error: true
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


collections:
  portfolio:
    output: true
    permalink: /:path/
    order:
      - Unbound.md
      - Metro-Awakening.md
      - Deliver-Us-Mars.md


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      masthead: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      masthead: true

