# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "catppuccin_latte", "catppuccin_mocha"

# Site Settings
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "Stanley Lageweg"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Stanley Lageweg"
description              : "Senior Game Programmer"
url                      : "https://stanleylageweg.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "StanleyLageweg/StanleyLageweg.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
words_per_minute         : 200
enable_copy_code_button  : # true, false (default)
copyright                : "Stanley Lageweg" # "copyright" name, defaults to site.title
copyright_url            : "https://github.com/StanleyLageweg/stanleylageweg.github.io/blob/master/LICENSE" # "copyright" URL, defaults to site.url
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
og_image_alt             : # Alt text for Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Person" # Person or Organization (defaults to Person)
  name                   : "Stanley Lageweg" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Stanley Lageweg"
  avatar           : "/assets/images/stanley.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Senior Game Programmer"
  location         : "Alphen aan den Rijn, Netherlands"
  email            :
  linkedin         : "stanley-lageweg"
  # fediverse      : "@you@instance.social"  # used for fediverse:creator meta tag
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-square-facebook"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - LICENSE
  - NOTICE.md
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache


collections:
  portfolio:
    output: true
    permalink: /:path/
    order:
      - Metro-Awakening.md
      - Deliver-Us-Mars.md


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      masthead: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      masthead: true

