name: Build the site

on:
  workflow_call:
    inputs:
      upload_artifact:
        description: Whether to upload the built site as a GitHub Pages artifact.
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            /*
            !/performance-profiling
          sparse-checkout-cone-mode: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Node.js packages
        run: npm ci

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libvips libheif-plugin-aomenc

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload pages artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-pages-artifact@v5
