name: Build and deploy the site to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: _site

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
